### ISSUE TITLE
Automate the process of discovering the apiDocumentation

### ISSUE THREAD

**Issue by shravandoda** [HTTP-APIs/hydra-python-agent#102]
At present, the agent has been hard coded to fetch the API Doc by appending `/vocab` to the URL provided. This not aligned with Hydra Spec. The agent should be able to extract the link to API documentation from the homepage of API publisher by looking for Link header in HTTP response with relationship type `http://www.w3.org/ns/hydra/core#apiDocumentation`

**Comment by Abhimanyu121** [comment]
I am really new to hydra ecosystem but I would like to work on this, it might take me some time though (since I am new).

**Comment by shravandoda** [comment]
I'd recommend you go through the core vocab and get acquainted with the issue. Here's the link -> https://www.hydra-cg.com/spec/latest/core/](Hydra Core Vocabulary)

**Comment by Abhimanyu121** [comment]
Thank you, I will

**Comment by Guttz** [comment]
Welcome @Abhimanyu121, first take some time to get familiar with the concepts at http://www.hydraecosystem.org/ and other doubts you might have. [We are available at Gitter](https://gitter.im/HTTP-APIs/Lobby).

**When** you feel a bit more comfortable, I have a tip for the issue. Currently, the Agent simply uses vocab(line 29, graphutils_operations.py):

![image](https://user-images.githubusercontent.com/11739405/62895050-6c012f00-bd24-11e9-8339-fa853daf5194.png)

However, the agent has already the ApiDoc available and you can go to self.api_doc['context']['context']['vocab'] and get the full address for the vocab :)

![image](https://user-images.githubusercontent.com/11739405/62895333-111c0780-bd25-11e9-903c-4f372e0d74b8.png)

**Comment by Abhimanyu121** [comment]
Thank you @Guttz , I will get familiar with all the concepts and make a pr soon :D

**Comment by vcode11** [comment]
Can I work on this?

**Comment by xadahiya** [comment]
You don't need to ask for permission, feel free to work on anything you want.

**Comment by shravandoda** [comment]
> I'd recommend you go through the core vocab and get acquainted with the issue. Here's the link -> [Hydra Core Vocabulary](https://www.hydra-cg.com/spec/latest/core/)

@vcode11 kindly take a look at this. You'll find it helpful

**Comment by kss682** [comment]
Can I work on this issue , I am new to hydra . I have set up the env and went through the docs.

**Comment by shravandoda** [comment]
> Can I work on this issue , I am new to hydra . I have set up the env and went through the docs.

No need to ask @kss682.

**Comment by chrizandr** [comment]
Is this issue resolved? @xadahiya @Guttz
