### ISSUE TITLE
Improve project layout

### ISSUE THREAD

**Issue by motormouthdoda** [HTTP-APIs/hydra-python-agent#103]
Currently, the project is just a bunch of files in a folder. Before we start implementing new features and rewrite the agent's code, its imperative that we improve the project layout so that it's easier to organize and test the project. The layout should be extensible to the new functionalities that will be added.

**Comment by ShravanDoda** [comment]
One of the ways could be to organize the code into 3 parts -> primary (sort of like the core), secondary (querying, fetching etc) and bookkeeping code (interface). The tests could be organized in the similar manner.

**Comment by Guttz** [comment]
The project design/layout is being discussed [in this doc](https://docs.google.com/document/d/189TNgNHFG79U68fJtqz12lhACDvMqzYEUIShv9Bl2RI/edit?usp=sharing). Please input your comments there.
