### ISSUE TITLE
[Discussion] Members properties storing

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent#110]
Currently, the way properties are stored in a node that is a member of a collection is:

![image](https://user-images.githubusercontent.com/11739405/59758745-e6ff1980-928e-11e9-8f85-8dc87a1295d2.png)

![image](https://user-images.githubusercontent.com/11739405/59758354-077aa400-928e-11e9-8a8f-eae8a8634cc7.png)

Two things happens due to this: 

- This stores in every node some a duplicate information available already available in the apidoc, by using type I can always go to the api doc for properties names and operations.

- Nodes cannot be queried by their properties like model, for example. That because the value of model is stored as part of a string inside a property called "properties_values", so "model" it's not a property of the node itself. 

---

It seems somehow faceted indexing is related to this and was used to these kinds of situations to provide a solution for more complex queries. [As stated in Sandeep's blog post](https://medium.com/w3c-hydra-development-community/querying-mechanism-15850bba6606) 

> faceted indexing... which can filter using expressions like: “model equals xyz” and “name equals Drone1 and model equals xyz”

However, with Redis open cypher, if we set the properties for the member collection, [we could do all kinds of combinations](https://oss.redislabs.com/redisgraph/commands/#where), for example:

> GRAPH.QUERY apidoc "MATCH (p) WHERE (p.model = 'model3' AND p.speed > 32) RETURN p"

Or even more complex queries, filtering by the type of relations, properties of connected nodes and etc.

**Comment by Mec-iS** [comment]
> This stores in every node some a duplicate information available already available in the apidoc, by using type I can always go to the api doc for properties names and operations.

Absolutely we don't want to store information twice. Nodes should store only store the properties enlisted in `5) p.properties` I suppose.

**Comment by Guttz** [comment]
I agree with not storing this information. In my opinion, we should change this so the node should contain the same information that hydrus has for a resource, in the Drone example above:

![image](https://user-images.githubusercontent.com/11739405/59796587-26088b80-92de-11e9-90c9-9d904f68edf1.png)

Each of them as a property of the node so they can be queried properly.

**Comment by Guttz** [comment]
@chrizandr @xadahiya @sandeepsajan0 Is there anything I'm missing for this implementation?

 Also about the faceted indexing, was the open cypher implementation not complete back then/something like this or is there another advantage I'm not aware of?

**Comment by Mec-iS** [comment]
beside the functionalities provided by Redisgraph, we can also build faceted indexes on single properties. This is connected to agent's configuration, so in theory developers can set a flag in a configuration file to define indexes on particularly important properties.

**Comment by Guttz** [comment]
As we agreed on the call I will make the architecture modification so we now use the proper structure as of hydrus, like the image above https://github.com/HTTP-APIs/hydra-python-agent/issues/110#issuecomment-503726997. 

More than that, I'll check how's the current state of linking embedded URIs in the object, in the example above the DroneState, and might open an issue depending on the current implementation.

**Comment by Guttz** [comment]
With the new implementation, this architecture was implemented and properties can be directly queried in the graph. 

For the recursive node linking I've created a new issue -> https://github.com/HTTP-APIs/hydra-python-agent/issues/113
