### ISSUE TITLE
Redis Graph py Result-set format update

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent#112]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Our repo is currently using redisgraph-py:1.7 and there's a breaking change to 2.0 because they've changed the Result-set into a more easily processable output.. Which might be interesting.

### Mailing update and ref:
https://groups.google.com/forum/#!topic/redisgraph/UHC_f3a7Ldo
https://oss.redislabs.com/redisgraph/result_structure/

### Modifications to be made:
redisgraph-py - 1.7 -> 2.0 https://github.com/RedisGraph/redisgraph-py/releases 
redisgraph docker image -  1.2.2 -> "edge"  https://hub.docker.com/r/redislabs/redisgraph/tags

**Comment by xadahiya** [comment]
We should deal with this on a priority basis then.

**Comment by Mec-iS** [comment]
yea we cannot get stuck to the old version at this point

**Comment by Guttz** [comment]
Yup, I agree with that. Will try to make the upgrade for the repo.

**Comment by Guttz** [comment]
Almost finished updating, the new response format is better and already does some code I had to program.

However, there are still some loose things, opened an issue over there -> https://github.com/RedisGraph/redisgraph-py/issues/42. Will clear some things out before moving on with this.
