### ISSUE TITLE
Outdated Chat Room link

### ISSUE THREAD

**Issue by vcode11** [HTTP-APIs/hydra-python-agent#130]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

The current link to chat in contributing.md refers to gitter but organization has moved to a slack channel.

### Expected Behaviour:

Link to the slack channel.

### Steps to reproduce:

Click on help in the chat in CONTRIBUTING.md

### Do you want to work on this issue?

Yes

**Comment by vcode11** [comment]
This is a common issue across all hydra repositories that have a CONTRIBUTING.md.

**Comment by chrizandr** [comment]
We've made those changes in the SoD branch. There is also some UI revamp there. It will be published in master soon. Thanks :)
