### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pip._internal.download'

### ISSUE THREAD

**Issue by Mikhaelle** [HTTP-APIs/hydra-python-agent#140]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
following the steps described to run the application in the Read-me after running python3 setup.py install I received an error.

Traceback (most recent call last):
File "setup.py", line 8, in <module>
from pip._internal.download import PipSession
ModuleNotFoundError: No module named 'pip._internal.download'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "setup.py", line 10, in <module>
from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req' 

It'is the same issue report in #133 but i'm reporting the problem because it appeared again

### Expected Behaviour:
Hydra API client will set up.

### Steps to reproduce:
Follow steps given in README.md
Run with sudo
Python3 version:
3.6.9

pip version:
20.0.2

### Do you want to work on this issue?
yes

**Comment by Mec-iS** [comment]
same as #133 
see also #134
