### ISSUE TITLE
Error when running python hydra agent 

### ISSUE THREAD

**Issue by PrajwalM2212** [HTTP-APIs/hydra-python-agent#72]
<img width="1600" alt="screen shot 2019-01-22 at 10 50 18 pm" src="https://user-images.githubusercontent.com/30733262/51553838-e0b07100-1e99-11e9-87a7-7c9bcd4c197d.png">

Hydra connection expects a` string` as a value but a `dictionary` is passed instead.

**Comment by ShravanDoda** [comment]
This is what I was talking about @PrajwalM2212

**Comment by Mec-iS** [comment]
@sandeepsajan0 please give advice

**Comment by sandeepsajan0** [comment]
I don't think, there is any that type of error. Anybody else is getting the same error?  @PrajwalM2212  Can you provide me a full log(include input url)? And make sure you haven't changed anything in your local.

**Comment by ShravanDoda** [comment]
@sandeepsajan0 `redis_connection.set("EntryPoint", entrypoint_properties)` -- `entrypoint_properties` is a dictionary. Line-58, hydra_graph.py

**Comment by ShravanDoda** [comment]
I don't see why are we setting `EntryPoint` as key separately when we have an entrypoint node in the redisgraph. It's not used anywhere in the code. Moreover, the user is not going to get the properties of entrypoint node from `redis-cli`. I think we should just remove this line of code. Maybe we should create another query which fetches the details about entrypoint node (something like `show entrypoint`).

**Comment by sandeepsajan0** [comment]
Yes @ShravanDoda, I think it'll be a better way. If this line is making any error we can remove it by an additional query also. Because now I can't see any role of this key and I don't remember why we have put it there.

**Comment by sandeepsajan0** [comment]
fixed in #94
