### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by sandeepsajan0** [HTTP-APIs/hydra-python-agent#95]
We have to update README.md for renamed `python-hydra-agent`->`hydra-python-agent`.

**Comment by ShravanDoda** [comment]
@Mec-iS kindly change the code in README. It hasn’t been changed from python-hydra-agent.

**Comment by Mec-iS** [comment]
The README in `master` is correct. This issue is closed.

**Comment by ShravanDoda** [comment]
The link provided in the demos haven't been changed. Kindly take a look.
Specifically  -- 
`git clone https://github.com/HTTP-APIs/python-hydra-agent.git` should be 
`git clone https://github.com/HTTP-APIs/hydra-python-agent.git`

**Comment by Mec-iS** [comment]
Fixed
