### ISSUE TITLE
Port all operations to use Redis

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-python-agent#99]
All operations on the graph shall be using Redis (so every operation on the graph shall issue one or more Redis command). The only data stored in memory should be the API endpoints graph for now (but possibly it will be in the datastore eventually as well).

Please take a look in depth to closed issues for reference:
* https://github.com/HTTP-APIs/hydra-python-agent/issues/11
* https://github.com/HTTP-APIs/hydra-python-agent/issues/22
* https://github.com/HTTP-APIs/hydra-python-agent/issues/18

**Comment by Guttz** [comment]
Could someone briefly cite what's yet to be ported to Redis? @Mec-iS @ShravanDoda @sandeepsajan0 
 
Currently collection, Endpoints and members currently seem to be added to Redis, also queries are made with commands to Redis and the structure appear conformant with issues #11, #22 and #18.

**Comment by ShravanDoda** [comment]
> All operations on the graph shall be using Redis

^^

**Comment by Guttz** [comment]
Yeah, I get that all operations shall be using Redis, perhaps I didn't express myself well enough. 

From checking the Agents code the operations already seem to be issuing Redis commands as the  "get_collection_properties" method at the image below.  

![image](https://user-images.githubusercontent.com/11739405/55280526-f8d3bf00-5326-11e9-92d7-4e0d900fa3c3.png)

Can you mention which part of the architecture is yet to be ported/should issue Redis commands and currently isn't?

**Comment by Mec-iS** [comment]
all the HTTP methods will perform some sort of operation on the graph. The graph is stored in Redisgraph and shall be using its datastructures and related operations.

**Comment by ShravanDoda** [comment]
For example, connecting different nodes in the graph hasn't been ported out to `Redis` yet.

**Comment by Guttz** [comment]
Oh, that makes sense. Thanks for the clarifications @Mec-iS @ShravanDoda

**Comment by Mec-iS** [comment]
Please take a look to [this page](http://interactivepython.org/runestone/static/pythonds/Graphs/Implementation.html); it defines all the necessary operations though it stores them by allocating Python objects. We want those operations to be performed by Redis, so any of those methods implemented in the `Vertex` `Edge` and `Graph` classes should issue a Redisgraph command.

Remember that in RDF triples (subject-predicate-object, vertex-edge-vertex) are the way of representing data; the result is a directed graph from subjects to objects of triples, with all its [mathematical properties](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)).
To give some other references: the two main family of algorithms that are used to search a graph are "Breadth-first" or "Depth-first", Redigraph uses these algos and others to make its commands to return data from the graph. Redis as a datastore in general allows much more efficient and scalable memory management so it makes possible to scale up to billions of vertices and edges (providing high-availability and replication by design). Major [Redis data-structures](https://redis.io/topics/data-types-intro) are involved in storing [adjacency lists](https://en.wikipedia.org/wiki/Adjacency_list) for the graph.

**Comment by Mec-iS** [comment]
#109
